//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Info
    {
        public int AutoID { get; set; }
        public int RegID { get; set; }
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string DepartmentName { get; set; }
        public string SectionName { get; set; }
        public string Designation { get; set; }
        public Nullable<double> Salary { get; set; }
    }
}
